# -*- coding: utf-8 -*-
"""Copy of OCRusingTesseract.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Y2y3cvba1epZmiuBgLTaqKbqSoqbUvD
"""

import pytesseract
try:
    from PIL import Image
except ImportError:
    import Image
import re
from datetime import datetime


def imageInfo(img_path):
    extractedInformation = pytesseract.image_to_string(Image.open(img_path))
    # extractedInformation_th = pytesseract.image_to_string(Image.open(img_path),lang="tha")

    test_str = extractedInformation

    # searching string
    match_str = re.search(r'\d{2}\s\w+\s\d{4}', test_str)
    match_amout = re.search(r'\b(?:\d{1,3}(?:,\d{3})*|\d+)\.\d{2}\b',test_str)
    match_date = re.search(r'(\d{2}:\d{2})',test_str)
    print(match_str.group()+"++++++"+match_date.group()+"++++++"+match_amout.group())
    

imageInfo('./images/IMG_2411.JPG')
